using System;
using HaritaApp.API.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HaritaApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508120000_EnsureRoutesWaypoints")]
    public partial class EnsureRoutesWaypoints : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Routes"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" text NOT NULL,
                    ""GeometryType"" text NOT NULL,
                    ""Waypoints"" text NULL,
                    ""Geoloc"" geometry NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UserId"" integer NOT NULL,
                    CONSTRAINT ""PK_Routes"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Routes_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                );

                ALTER TABLE IF EXISTS ""Routes""
                    ADD COLUMN IF NOT EXISTS ""Waypoints"" text NULL;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_indexes
                        WHERE schemaname = 'public'
                          AND indexname = 'IX_Routes_UserId'
                    ) THEN
                        CREATE INDEX ""IX_Routes_UserId"" ON ""Routes"" (""UserId"");
                    END IF;
                END $$;
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE IF EXISTS \"Routes\" DROP COLUMN IF EXISTS \"Waypoints\";");
        }
    }
}
